# NumPy

In [2]:
import numpy as np

In [2]:
print(np.__version__)


2.5.1


### Create Array

In [ ]:
#1d array
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [4]:
#2d array
arr =np.array([[1,2,3],[2,5,8]])
print(arr)

[[1 2 3]
 [2 5 8]]


In [5]:
#3d array
arr =np.array([
    [  [1,2],
       [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
    ])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [7]:
arr = np.array([[1,2,3],[5,7,9]])
print(arr.ndim)

2


In [10]:
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(2, 3)
6
int64
8


In [13]:
#Zeros
print(np.zeros((5,6)))
#ones
print(np.ones((2,5)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#identity Matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
#Full
print(np.full((3,3),100))

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [18]:
#Random Integer
print(np.random.randint(1,100,(4,4)))

[[17 51 30 36]
 [15 62 25 21]
 [49 68 23 47]
 [91 16 49 18]]


### Sequence Arrays

In [20]:
print(np.arange(1,20))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
print(np.arange(1,20,2))

[ 1  3  5  7  9 11 13 15 17 19]


### mathematical operations

In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [4]:
arr = np.array([10,20,30,40])
print(np.sum(arr))
print(np.mean(arr))

100
25.0


### where

In [5]:
arr = np.array([10,20,30,40])
print(np.where(arr>20))

(array([2, 3]),)
